apiVersion: apps/v1
kind: Deployment
metadata:
  name: casual
  labels:
    app: casual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casual
  template:
    metadata:
      labels:
        app: casual
    spec:
      containers:
      - name: casual
        image: casual-domain-1.5.13:latest
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        imagePullPolicy: Never
        ports:
        - containerPort: 7771
        - containerPort: 7780
        env:
          - name: CASUAL_LOG
            value: warning | error
